### ISSUE TITLE
Promote master build to snapshots

### ISSUE THREAD

**Issue by akurtakov** [eclipse-cbi/p2repo-analyzers#29]
Continuation of https://github.com/eclipse-cbi/p2repo-analyzers/pull/27#issuecomment-1396939445 so we get automated deployment on master build.

**Comment by merks** [comment]
Never mind!  I was smart enough to already do this:

https://github.com/eclipse-cbi/p2repo-analyzers/blob/a215bd036abbfb050775b1371cba455dfda243e7/Jenkinsfile#L82-L93

But not smart enough to remember doing it.  😱 

So there are lots of builds from today already:

![image](https://user-images.githubusercontent.com/208716/213452267-ca3d0560-e2d9-4ebf-aa4c-9d5e59f14f13.png)

Sorry about that...

**Comment by akurtakov** [comment]
OK, closing in this case.
